name: Haskell Stack CI

on: [workflow_dispatch]

jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: adius/tasklite:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  # windows:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v1

  #     - name: Install stack
  #       shell: cmd
  #       run: choco install haskell-stack

  #     - name: Install dependencies
  #       run: stack install tasklite-core

  #     - name: Upload Windows Release
  #       uses: actions/upload-artifact@v1
  #       with:
  #         path: '%APPDATA%\local\bin\tasklite.exe'
  #         name: tasklite_windows_x86_64.exe

  # publish:
  #   needs: build
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - name: Set env with output of `git describe`
  #       run: echo ::set-env name=GIT_DESCRIBE::$(git describe)
  #
  #     - name: Create Release
  #       id: create_release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         tag_name: ${{ env.GIT_DESCRIBE }}
  #         release_name: Release ${{ env.GIT_DESCRIBE }}
  #         body: ${{ github.event.commits[0].message }}
  #         draft: false
  #         prerelease: false
